2021-03-02 18:38:42 [scrapy.utils.log] INFO: Scrapy 2.1.0 started (bot: ARGUS)
2021-03-02 18:38:43 [scrapy.utils.log] INFO: Versions: lxml 4.6.1.0, libxml2 2.9.10, cssselect 1.1.0, parsel 1.6.0, w3lib 1.22.0, Twisted 20.3.0, Python 3.7.6 | packaged by conda-forge | (default, Dec 26 2019, 23:46:52) - [Clang 9.0.0 (tags/RELEASE_900/final)], pyOpenSSL 19.1.0 (OpenSSL 1.1.1d  10 Sep 2019), cryptography 2.8, Platform Darwin-18.7.0-x86_64-i386-64bit
2021-03-02 18:38:43 [scrapy.crawler] INFO: Overridden settings:
{'AJAXCRAWL_ENABLED': True,
 'BOT_NAME': 'ARGUS',
 'COMPRESSION_ENABLED': False,
 'CONCURRENT_ITEMS': 200,
 'CONCURRENT_REQUESTS': 100,
 'COOKIES_ENABLED': False,
 'DOWNLOAD_MAXSIZE': 10000000,
 'DOWNLOAD_TIMEOUT': 20,
 'LOG_FILE': 'logs/ARGUS/dualspider/2b21d5987b6911ebaf3134363b7bab66.log',
 'LOG_LEVEL': 'INFO',
 'NEWSPIDER_MODULE': 'ARGUS.spiders',
 'REACTOR_THREADPOOL_MAXSIZE': 30,
 'RETRY_ENABLED': False,
 'SPIDER_MODULES': ['ARGUS.spiders']}
2021-03-02 18:38:43 [scrapy.extensions.telnet] INFO: Telnet Password: 2c61e4bb5c9d64c8
2021-03-02 18:38:43 [py.warnings] WARNING: /Users/parnianshahkar/Downloads/miniconda3/lib/python3.7/site-packages/scrapy/extensions/feedexport.py:210: ScrapyDeprecationWarning: The `FEED_URI` and `FEED_FORMAT` settings have been deprecated in favor of the `FEEDS` setting. Please see the `FEEDS` setting docs for more details
  exporter = cls(crawler)

2021-03-02 18:38:43 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2021-03-02 18:38:54 [fake_useragent] WARNING: Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "/Users/parnianshahkar/Downloads/miniconda3/lib/python3.7/site-packages/fake_useragent/utils.py", line 67, in get
    context=context,
  File "/Users/parnianshahkar/Downloads/miniconda3/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/parnianshahkar/Downloads/miniconda3/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Users/parnianshahkar/Downloads/miniconda3/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Users/parnianshahkar/Downloads/miniconda3/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Users/parnianshahkar/Downloads/miniconda3/lib/python3.7/urllib/request.py", line 1347, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/Users/parnianshahkar/Downloads/miniconda3/lib/python3.7/urllib/request.py", line 1322, in do_open
    r = h.getresponse()
  File "/Users/parnianshahkar/Downloads/miniconda3/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/Users/parnianshahkar/Downloads/miniconda3/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/Users/parnianshahkar/Downloads/miniconda3/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/parnianshahkar/Downloads/miniconda3/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/parnianshahkar/Downloads/miniconda3/lib/python3.7/site-packages/fake_useragent/utils.py", line 166, in load
    verify_ssl=verify_ssl,
  File "/Users/parnianshahkar/Downloads/miniconda3/lib/python3.7/site-packages/fake_useragent/utils.py", line 122, in get_browser_versions
    verify_ssl=verify_ssl,
  File "/Users/parnianshahkar/Downloads/miniconda3/lib/python3.7/site-packages/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
2021-03-02 18:38:55 [scrapy_fake_useragent.middleware] INFO: Using '<class 'scrapy_fake_useragent.providers.FakeUserAgentProvider'>' as the User-Agent provider
2021-03-02 18:38:55 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy_fake_useragent.middleware.RandomUserAgentMiddleware',
 'scrapy.downloadermiddlewares.ajaxcrawl.AjaxCrawlMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2021-03-02 18:38:55 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2021-03-02 18:38:55 [scrapy.middleware] INFO: Enabled item pipelines:
['ARGUS.pipelines.DualPipeline']
2021-03-02 18:38:55 [scrapy.core.engine] INFO: Spider opened
2021-03-02 18:38:55 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2021-03-02 18:38:55 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2021-03-02 18:38:58 [filelock] INFO: Lock 4677209424 acquired on /Users/parnianshahkar/.cache/python-tldextract/3.7.6.final__miniconda3__c4b0bd__tldextract-3.1.0/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
2021-03-02 18:38:58 [filelock] INFO: Lock 4677932880 acquired on /Users/parnianshahkar/.cache/python-tldextract/3.7.6.final__miniconda3__c4b0bd__tldextract-3.1.0/urls/62bf135d1c2f3d4db4228b9ecaf507a2.tldextract.json.lock
2021-03-02 18:38:59 [filelock] INFO: Lock 4677932880 released on /Users/parnianshahkar/.cache/python-tldextract/3.7.6.final__miniconda3__c4b0bd__tldextract-3.1.0/urls/62bf135d1c2f3d4db4228b9ecaf507a2.tldextract.json.lock
2021-03-02 18:38:59 [filelock] INFO: Lock 4677209424 released on /Users/parnianshahkar/.cache/python-tldextract/3.7.6.final__miniconda3__c4b0bd__tldextract-3.1.0/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
2021-03-02 18:38:59 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x115b49810>>
Traceback (most recent call last):
  File "/Users/parnianshahkar/Downloads/miniconda3/lib/python3.7/site-packages/scrapy/utils/defer.py", line 161, in maybeDeferred_coro
    result = f(*args, **kw)
  File "/Users/parnianshahkar/Downloads/miniconda3/lib/python3.7/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/Users/parnianshahkar/Downloads/miniconda3/lib/python3.7/site-packages/scrapy/extensions/feedexport.py", line 291, in item_scraped
    slot.exporter.export_item(item)
  File "/Users/parnianshahkar/Downloads/miniconda3/lib/python3.7/site-packages/scrapy/exporters.py", line 91, in export_item
    itemdict = dict(self._get_serialized_fields(item))
  File "/Users/parnianshahkar/Downloads/miniconda3/lib/python3.7/site-packages/scrapy/exporters.py", line 65, in _get_serialized_fields
    field_iter = item.keys()
AttributeError: 'NoneType' object has no attribute 'keys'
2021-03-02 18:39:01 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x115b49810>>
Traceback (most recent call last):
  File "/Users/parnianshahkar/Downloads/miniconda3/lib/python3.7/site-packages/scrapy/utils/defer.py", line 161, in maybeDeferred_coro
    result = f(*args, **kw)
  File "/Users/parnianshahkar/Downloads/miniconda3/lib/python3.7/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/Users/parnianshahkar/Downloads/miniconda3/lib/python3.7/site-packages/scrapy/extensions/feedexport.py", line 291, in item_scraped
    slot.exporter.export_item(item)
  File "/Users/parnianshahkar/Downloads/miniconda3/lib/python3.7/site-packages/scrapy/exporters.py", line 91, in export_item
    itemdict = dict(self._get_serialized_fields(item))
  File "/Users/parnianshahkar/Downloads/miniconda3/lib/python3.7/site-packages/scrapy/exporters.py", line 65, in _get_serialized_fields
    field_iter = item.keys()
AttributeError: 'NoneType' object has no attribute 'keys'
2021-03-02 18:39:01 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x115b49810>>
Traceback (most recent call last):
  File "/Users/parnianshahkar/Downloads/miniconda3/lib/python3.7/site-packages/scrapy/utils/defer.py", line 161, in maybeDeferred_coro
    result = f(*args, **kw)
  File "/Users/parnianshahkar/Downloads/miniconda3/lib/python3.7/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/Users/parnianshahkar/Downloads/miniconda3/lib/python3.7/site-packages/scrapy/extensions/feedexport.py", line 291, in item_scraped
    slot.exporter.export_item(item)
  File "/Users/parnianshahkar/Downloads/miniconda3/lib/python3.7/site-packages/scrapy/exporters.py", line 91, in export_item
    itemdict = dict(self._get_serialized_fields(item))
  File "/Users/parnianshahkar/Downloads/miniconda3/lib/python3.7/site-packages/scrapy/exporters.py", line 65, in _get_serialized_fields
    field_iter = item.keys()
AttributeError: 'NoneType' object has no attribute 'keys'
2021-03-02 18:39:01 [scrapy.core.engine] INFO: Closing spider (finished)
2021-03-02 18:39:01 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 2156,
 'downloader/request_count': 9,
 'downloader/request_method_count/GET': 9,
 'downloader/response_bytes': 2112269,
 'downloader/response_count': 9,
 'downloader/response_status_count/200': 3,
 'downloader/response_status_count/301': 6,
 'elapsed_time_seconds': 6.345185,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2021, 3, 2, 15, 9, 1, 588750),
 'item_scraped_count': 3,
 'log_count/ERROR': 3,
 'log_count/INFO': 15,
 'log_count/WARNING': 2,
 'memusage/max': 103583744,
 'memusage/startup': 103583744,
 'response_received_count': 3,
 'scheduler/dequeued': 9,
 'scheduler/dequeued/memory': 9,
 'scheduler/enqueued': 9,
 'scheduler/enqueued/memory': 9,
 'start_time': datetime.datetime(2021, 3, 2, 15, 8, 55, 243565)}
2021-03-02 18:39:01 [scrapy.core.engine] INFO: Spider closed (finished)
